// Which brand folder a commercial belongs in, guessed from its file name. Used by
// `tv.cmd file` to sort the staging folder; first match wins, so specific brands come
// before the manufacturer catch-alls (Kellogg's, General Mills, Post). Add a line when
// a brand keeps coming up as "couldn't place".
const RULES = [
  [/big city slider/, "Big City Slider"],
  [/frosty o/, "Frosty O's"],
  [/cocopuffs|sonny gramps/, "Cocoa Puffs"],
  [/cap n crunch|smedley/, "Cap'n Crunch"],
  [/reese s|reeses|hayden menard|vanessa hudgens/, "Reese's Puffs"],
  [/alpha[- ]? ?bits|alphabits/, "Alpha-Bits"],
  [/cocoa krispies/, "Cocoa Krispies"],
  [/cocoa loops/, "Cocoa Loops"],
  [/sugar crisp|golden crisp|sugar bear|psychedelic sugar/, "Sugar Crisp"],
  [/sugar pops|^pops commercial/, "Corn Pops"],
  [/quisp|quake|quangaroos/, "Quisp & Quake"],
  [/fiber ?one/, "Fiber One"],
  [/honey ?comb|honeycomb/, "Honeycomb"],
  [/pac[- ]?man cereal/, "Pac-Man Cereal"],
  [/king vitaman/, "King Vitaman"],
  [/french toast crunch|chocolate toast crunch|frosted toast crunch|powered donutz/, "French Toast Crunch"],
  [/ghostbusters cereal/, "Ghostbusters Cereal"],
  [/pink panther/, "Pink Panther Flakes"],
  [/strawberry shortcake/, "Strawberry Shortcake Cereal"],
  [/froo+t loop|froot ?loopy|loop winders/, "Froot Loops"],
  [/lucky goes to mars/, "Lucky Charms"],
  [/rainbow of colors/, "Froot Loops"],
  [/crispy c/, "Crispy Critters"],
  [/oreo (cookie|o s)/, "Oreo O's"],
  [/rabbit cops/, "Trix"],
  [/scooby doo and cereal/, "Scooby-Doo Cereal"],
  [/mr t cereal/, "Mr. T Cereal"],
  [/james coffey/, "James Coffey"],
  [/pack it lunch/, "Pack It"],
  [/scooby-doo|c mon scoob/, "Scooby-Doo"],
  [/sonic/, "Sonic"],
  [/musicspace|fired up|^pulse|the edge/, "Musicspace"],
  [/jump man/, "Jordan"],
  [/shire?ly temple/, "Shirley Temple"],
  [/honey nut cheerios|honey nut cherrios/, "Cheerios"],
  [/cheerios|cherrios|shreddies nesquik/, "Cheerios"],
  [/cinnamon (toast crunch|crunch)|ctc\b|cinnamon toast/, "Cinnamon Toast Crunch"],
  [/cinnamon jacks|apple ?jacks|apple and cinna|apple jack|a is for apple/, "Apple Jacks"],
  [/pop[ -]?tarts?/, "Pop-Tarts"],
  [/rice krispies|rice krispy/, "Rice Krispies"],
  [/raisin bran/, "Raisin Bran"],
  [/corn ?flakes|cornelius/, "Corn Flakes"],
  [/frosted flakes|tony the tiger|frosties/, "Frosted Flakes"],
  [/mini[- ]?wheats|frosted mini/, "Frosted Mini-Wheats"],
  [/froot ?loops|fruit loops|toucan sam/, "Froot Loops"],
  [/fruity pebbles|cocoa pebbles|cupcake pebbles|pebbles|bedrock/, "Pebbles"],
  [/cocoa puffs|cuckoo/, "Cocoa Puffs"],
  [/reese'?s? puffs|reeses puffs/, "Reese's Puffs"],
  [/count chocula|franken ?berry|boo ?berry|monster cereal|fruit brute/, "Monster Cereals"],
  [/lucky charms|floating ?charms/, "Lucky Charms"],
  [/\btrix\b/, "Trix"],
  [/corn pops/, "Corn Pops"],
  [/cookie crisp/, "Cookie Crisp"],
  [/golden grahams/, "Golden Grahams"],
  [/crispy critters/, "Crispy Critters"],
  [/\bkrave\b/, "Krave"],
  [/cap'?n'?s? crunch|captain crunch|\bcrunch ?berries/, "Cap'n Crunch"],
  [/special ?k\b/, "Special K"],
  [/honey bunches/, "Honey Bunches of Oats"],
  [/\bchex\b/, "Chex"],
  [/wheaties/, "Wheaties"],
  [/\btotal\b.*cereal|total (raisin|corn|whole)/, "Total"],
  [/\bkix\b/, "Kix"],
  [/\bsmacks\b|honey smacks|sugar smacks/, "Smacks"],
  [/life cereal|\blife\b.*mikey/, "Life"],
  [/oreo o'?s|oreo ?os/, "Oreo O's"],
  [/waffle crisp/, "Waffle Crisp"],
  [/just right/, "Just Right"],
  [/basic 4/, "Basic 4"],
  [/honey crunchers/, "Honey Crunchers"],
  [/geico/, "Geico"],
  [/state farm/, "State Farm"],
  [/aflac/, "Aflac"],
  [/progressive/, "Progressive"],
  [/oxiclean|billy mays/, "OxiClean"],
  [/mcdonald|filet-o-fish|filet o fish|happy meal|mcnugget/, "McDonalds"],
  [/burger king|bk\b.*spongebob|spongebob burger/, "Burger King"],
  [/subway/, "Subway"],
  [/quiznos/, "Quiznos"],
  [/old spice/, "Old Spice"],
  [/chef boyardee/, "Chef Boyardee"],
  [/capri ?sun/, "Capri Sun"],
  [/danimals/, "Danimals"],
  [/gushers/, "Gushers"],
  [/fruit by the foot/, "Fruit by the Foot"],
  [/lego/, "LEGO"],
  [/kidz bop/, "Kidz Bop"],
  [/j\.?g\.? wentworth/, "JG Wentworth"],
  [/jack in the box/, "Jack in the Box"],
  [/\bm ?& ?m|m_m|m m'?s|\bm ms\b|eminem/, "M&Ms"],
  [/scrubbing bubbles/, "Scrubbing Bubbles"],
  [/coca[- ]cola|\bcoke\b/, "Coca-Cola"],
  [/baby bottle pop/, "Baby Bottle Pop"],
  [/gerber/, "Gerber Life"],
  [/meow ?(mix|$)|^meow$|meow mix/, "Meow Mix"],
  [/pillow pets/, "Pillow Pets"],
  [/shirley temple/, "Shirley Temple"],
  [/zoobooks/, "Zoobooks"],
  [/free ?credit ?report/, "Free Credit Report"],
  [/fushigi/, "Fushigi Ball"],
  [/education connection/, "Education Connection"],
  [/empire (carpet|today)/, "Empire Today"],
  [/mesothelioma/, "Mesothelioma"],
  [/floam/, "Floam"],
  [/kmart|k mart/, "Kmart"],
  [/6 flags|six flags/, "Six Flags"],
  [/farmers only/, "Farmers Only"],
  [/wizard ?101/, "Wizard101"],
  [/nickelodeon|nicktoons|nick ?toons/, "Nickelodeon"],
  [/cartoon network/, "Cartoon Network"],
  [/toonami/, "Toonami"],
  [/disney channel/, "Disney Channel"],
  [/4kids/, "4Kids TV"],
  [/nintendo|game ?boy|\bwii\b|donkey kong|nintendo ds/, "Nintendo"],
  [/^m m |m m s |m m sexy/, "M&Ms"],
  [/lots (and )?lots of (trains|trucks)/, "James Coffey"],
  [/betty crocker/, "Betty Crocker"],
  [/monstercereals/, "Monster Cereals"],
  [/^hnc heist/, "Cheerios"],
  [/hasbro|disney cereal|disney's|kellogg s.*(disney|toy story|atlantis|monsters|finding|ice age|chicken little|avatar|sing 2|cars 2)|kelloggs cars 2/, "Kellogg's"],
  [/general mills|big g\b|satur-yay|cereal squad/, "General Mills"],
  [/quaker|crunchatize/, "Quaker"],
  [/nestle/, "Nestle"],
  [/winnie the pooh canadian|nabisco/, "Nabisco"],
  [/hunny b/, "Hunny B's"],
  [/post|aunt bea|ruff and reddy|archies|grape nut|oak flakes/, "Post"],
  [/kellogg|snap crackle|youruleschool|simpsons kellogg|garfield sponsored|early 80s kellogg|jimmy durante/, "Kellogg's"],
  [/cereal commercials from the 1960s|cereal commercial collection|classic 1960 s cereal|classic saturday morning|great 90 s cereal|more great cereal|cbs saturday morning|jackson 5/, "Cereal Compilations"],
  [/morning funnies/, "Morning Funnies"],
  [/bill ted/, "Bill & Ted's Cereal"],
  [/body buddies/, "Body Buddies"],
  [/c3po|star wars cereal/, "Star Wars Cereal"],
  [/cabbage patch/, "Cabbage Patch Cereal"],
  [/choco crunch/, "Choco Crunch"],
  [/cinnamon pops/, "Cinnamon Pops"],
  [/circus fun/, "Circus Fun"],
  [/zucosos/, "Zucosos"],
  [/kaboom/, "Kaboom"],
  [/corny snaps/, "Corny Snaps"],
  [/crispy wheats/, "Crispy Wheats 'n Raisins"],
  [/dunkin/, "Dunkin' Donuts"],
  [/freakies/, "Freakies"],
  [/gremlins cereal/, "Gremlins Cereal"],
  [/hidden treasures/, "Hidden Treasures"],
  [/ice cream cones cereal/, "Ice Cream Cones Cereal"],
  [/making food with heart/, "General Mills"],
  [/peanut butter crunch/, "Peanut Butter Crunch"],
  [/pesadilla/, "Pesadilla Pop"],
  [/rocky road cereal/, "Rocky Road Cereal"],
  [/smurf magic/, "Smurf Magic Berries"],
  [/spongebob squarepants cereal/, "SpongeBob Cereal"],
  [/swedish chef/, "Swedish Chef Cereal"],
  [/powerpuff/, "Powerpuff Girls Cereal"],
  [/waffelos/, "Waffelos"],
  [/barbie/, "Barbie"],
  [/gogurt/, "GoGurt"],
  [/\baxe\b/, "Axe"],
  [/band-aid/, "Band-Aid"],
  [/chuck e cheese/, "Chuck E. Cheese"],
  [/\bdell\b/, "Dell"],
  [/denny s/, "Denny's"],
  [/chips ahoy/, "Chips Ahoy"],
  [/ipod/, "Apple"],
  [/flintstones vitamins/, "Flintstones Vitamins"],
  [/fruitsnackia/, "Fruitsnackia"],
  [/gamefly/, "GameFly"],
  [/hershey/, "Hershey's"],
  [/honda/, "Honda"],
  [/beggin/, "Beggin' Strips"],
  [/k9 advantix/, "K9 Advantix"],
  [/muzzy/, "Muzzy"],
  [/orajel/, "Orajel"],
  [/chia pet/, "Chia Pet"],
  [/puffs plus/, "Puffs"],
  [/respect the pouch/, "Capri Sun"],
  [/ricola/, "Ricola"],
  [/sarah mclachlan/, "ASPCA"],
  [/shamwow/, "ShamWow"],
  [/skechers/, "Skechers"],
  [/smokey the bear/, "Smokey Bear"],
  [/stanley steemer/, "Stanley Steemer"],
  [/stuffies/, "Stuffies"],
  [/swiffer/, "Swiffer"],
  [/sylvan/, "Sylvan Learning"],
  [/tootsie/, "Tootsie Roll"],
  [/air hogs/, "Air Hogs"],
  [/bendaroos/, "Bendaroos"],
  [/blendy pens/, "Blendy Pens"],
  [/d-rex/, "D-Rex"],
  [/^goldfish/, "Goldfish"],
  [/hamburger helper/, "Hamburger Helper"],
  [/moon sand/, "Moon Sand"],
  [/mucinex/, "Mucinex"],
  [/nerf/, "Nerf"],
  [/hulu/, "Hulu"],
  [/brave and the bold/, "Batman The Brave and the Bold"],
  [/iron man/, "Iron Man Armored Adventures"],
  [/fill n flavor/, "Fill N Flavor"],
  [/big top cupcake/, "Big Top Cupcake"],
  [/bumpits/, "Bumpits"],
  [/chip wizard/, "Chip Wizard"],
  [/ez pour/, "EZ Pour"],
  [/headon/, "HeadOn"],
  [/moon shoes/, "Moon Shoes"],
  [/slap chop/, "Slap Chop"],
  [/snackmate/, "SnackMate"],
  [/bake pops/, "Bake Pops"],
  [/wraptastic/, "Wraptastic"],
  [/monster ballads/, "Monster Ballads"],
  [/buzz ballads/, "Buzz Ballads"],
  [/pure moods/, "Pure Moods"],
  [/ultimate love song/, "Ultimate Love Song Collection"],
  [/modern rock/, "Modern Rock CDs"],
  [/reflections of love/, "Reflections of Love"],
  [/kingdom hearts/, "Kingdom Hearts"],
  [/mirror s edge/, "Mirror's Edge"],
  [/chrysler/, "Chrysler"],
  [/jeep/, "Jeep"],
  [/dodge/, "Dodge"],
  [/\bford\b/, "Ford"],
  [/volkswagen/, "Volkswagen"],
  [/supermario/, "Nintendo"],
  [/physique/, "Physique"],
  [/attack on toddler/, "Attack on Toddler"],
  [/cini minis/, "Cini Minis"],
  [/crayon shin/, "Crayon Shin-chan"],
  [/darkwing duck pasta/, "Darkwing Duck Pasta"],
  [/marvin s magic/, "Marvin's Magic Drawing Board"],
  [/matsuoka/, "Matsuoka Shuzo"],
  [/1-800 collect/, "1-800 Collect"],
  [/optimum/, "Optimum"],
  [/password journal/, "Password Journal"],
  [/planters/, "Planters"],
  [/saf-t-swim/, "Saf-T-Swim"],
  [/uncle majic/, "Uncle Majic"],
];

const clean = (name) => name.replace(/ \[[A-Za-z0-9_-]{11}\]/, "").replace(/\.[a-z0-9]+$/i, "").replace(/_+/g, " ").replace(/\s+/g, " ").trim().toLowerCase();

// "Old_Spice_Mom_Song [jlpLJptwUc0].mp4" -> "Old Spice"; null when nothing matches.
export function brandOf(fileName) {
  const c = clean(fileName);
  for (const [re, brand] of RULES) if (re.test(c)) return brand;
  return null;
}
